# Generated by Django 3.2.19 on 2023-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10, verbose_name='Держномер')),
                ('car_model', models.CharField(max_length=20, verbose_name='Марка')),
                ('car_color', models.CharField(max_length=20, verbose_name='Колір')),
                ('position', models.CharField(max_length=20, verbose_name='Стоянка')),
                ('status', models.CharField(max_length=10, verbose_name='Стоянка')),
                ('child_seat', models.BooleanField(verbose_name='Крісло')),
                ('trunk', models.BooleanField(verbose_name='Багаж')),
                ('smoking', models.BooleanField(verbose_name='Курець')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
            },
        ),
    ]
