# Generated by Django 3.2.19 on 2023-05-28 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10, verbose_name='Держномер')),
                ('car_model', models.CharField(max_length=20, verbose_name='Марка')),
                ('car_color', models.CharField(max_length=20, verbose_name='Колір')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Стоянка')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('child_seat', models.BooleanField(verbose_name='Крісло')),
                ('trunk', models.BooleanField(verbose_name='Багаж')),
                ('smoking', models.BooleanField(verbose_name='Курець')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Телефон')),
                ('address_from', models.CharField(max_length=20, verbose_name='Звідки')),
                ('address_to', models.CharField(max_length=20, verbose_name='Куди')),
                ('cost', models.FloatField(null=True, verbose_name='Ціна')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=30, verbose_name='Коментар')),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oper.drivers')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
