# Generated by Django 3.2.19 on 2023-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
    ]
