# Generated by Django 3.2.19 on 2023-05-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oper.drivers'),
        ),
    ]
