# Generated by Django 3.2.19 on 2023-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0002_alter_orders_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('NP', 'Не Працює'), ('CH', 'Черга'), ('OR', 'Замовлення')], default='NP', max_length=10, verbose_name='Статус'),
        ),
    ]
