# Generated by Django 3.2.19 on 2023-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0003_alter_drivers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('0NP', 'Не Працює'), ('CH', 'Черга'), ('OR', 'Замовлення')], default='0NP', max_length=10, verbose_name='Статус'),
        ),
    ]
