# Generated by Django 3.2.19 on 2023-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0004_alter_drivers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('Не Працює', 'Np'), ('CH', 'Черга'), ('OR', 'Замовлення')], default='Не Працює', max_length=10, verbose_name='Статус'),
        ),
    ]
