# Generated by Django 3.2.19 on 2023-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0006_alter_drivers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PN', 'Прийнято'), ('NU', 'Немає'), ('VD', 'В дорозі'), ('CK', 'Чекає'), ('VK', 'Виконнаня'), ('VN', 'Виконано'), ('VU', 'Відмінено')], default='PN', max_length=10, verbose_name='Статус'),
        ),
    ]
