# Generated by Django 3.2.19 on 2023-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0007_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('Не Працює', 'Не Працює'), ('Черга', 'Черга'), ('Замовлення', 'Замовлення')], default='Не Працює', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Прийнято', 'Прийнято'), ('Немає', 'Немає'), ('В дорозі', 'В дорозі'), ('Чекає', 'Чекає'), ('Виконнаня', 'Виконнаня'), ('Виконано', 'Виконано'), ('Відмінено', 'Відмінено')], default='Прийнято', max_length=10, verbose_name='Статус'),
        ),
    ]
